[platformio]
default_envs = pico2
src_dir = examples/00B_Hardware_Setup

[env]
framework = arduino
build_unflags = -std=gnu++11
build_flags = -std=gnu++17
lib_extra_dirs = .
monitor_speed = 115200
extra_scripts = pre:scripts/package_sdk.py

[env:pico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
board_build.core = earlephilhower
lib_deps =
    https://github.com/adafruit/Adafruit_MPU6050.git
    https://github.com/adafruit/Adafruit_BusIO.git
    https://github.com/adafruit/Adafruit_Sensor.git
    https://github.com/mikalhart/TinyGPSPlus.git
    https://github.com/earlephilhower/ESP8266Audio.git

; ESP32 builds can use the same selected example when its hardware
; configuration is changed to ESP32-compatible pins.
[env:esp32dev]
platform = espressif32
board = esp32dev
